var res = {
    hp: "res/体力.png",
    skill: "res/技.png",
    slime_green_frames: "res/slime_green_frames.png",
    opsakebi: "res/opsakebi.mp3",
    titlebgm: "res/titlebgm.mp3",
    opvoice: "res/opvoice.mp3",
    opken: "res/OPの剣の音.mp3",
    stagebgm: "res/stagebgm.mp3",
    ui_panels: "res/ui_panels.png",
    leftbutton_png: "res/leftbutton.png",
    player_sheet: "res/sir_awesome_frames.png",
    player_plist: "res/player.plist",
    player2_plist: "res/player2.plist",
    rightbutton_png: "res/rightbutton.png",
    background_front: "res/background_front.png",
    background_back: "res/background_back.png",
    background_png: "res/background_back.png",
    block_png: "res/block48X48.png",
    bat_frames: "res/bat_frames.png",
    tati: "res/おっさん立ち.png",
    aruki1: "res/おっさん歩き1.png",
    aruki2: "res/おっさん歩き2.png",
    aruki3: "res/おっさん歩き3.png",
    aruki4: "res/おっさん歩き4.png",
    tatikougeki1: "res/おっさん立ち攻撃1.png",
    tatikougeki2: "res/おっさん立ち攻撃2.png",
    janp1: "res/おっさんジャンプ1.png",
    janp2: "res/おっさんジャンプ2.png",
    janp3: "res/おっさんジャンプ3.png",
    background_light_shafts: "res/background_light_shafts.png",
    curtain: "res/curtain.png",
    title: "res/title.png",
    dead_sword: "res/dead_sword.png",
    siro: "res/白拝啓.png",
    glass_frames: "res/glass_frames.png",

    akatitlelight1: "res/赤タイトルの光1.png",
    akatitlelight2: "res/赤タイトルの光2.png",
    akatitlelight3: "res/赤タイトルの光3.png",
    akatitlelight4: "res/赤タイトルの光4.png",
    akatitlelight5: "res/赤タイトルの光5.png",
    akatitlelight6: "res/赤タイトルの光6.png",
    akatitlelight7: "res/赤タイトルの光7.png",
    toutitlelight1: "res/橙タイトルの光1.png",
    toutitlelight2: "res/橙タイトルの光2.png",
    toutitlelight3: "res/橙タイトルの光3.png",
    toutitlelight4: "res/橙タイトルの光4.png",
    toutitlelight5: "res/橙タイトルの光5.png",
    toutitlelight6: "res/橙タイトルの光6.png",
    toutitlelight7: "res/橙タイトルの光7.png",
    kititlelight1: "res/黄タイトルの光1.png",
    kititlelight2: "res/黄タイトルの光2.png",
    kititlelight3: "res/黄タイトルの光3.png",
    kititlelight4: "res/黄タイトルの光4.png",
    kititlelight5: "res/黄タイトルの光5.png",
    kititlelight6: "res/黄タイトルの光6.png",
    kititlelight7: "res/黄タイトルの光7.png",
    midorititlelight1: "res/緑タイトルの光1.png",
    midorititlelight2: "res/緑タイトルの光2.png",
    midorititlelight3: "res/緑タイトルの光3.png",
    midorititlelight4: "res/緑タイトルの光4.png",
    midorititlelight5: "res/緑タイトルの光5.png",
    midorititlelight6: "res/緑タイトルの光6.png",
    midorititlelight7: "res/緑タイトルの光7.png",
    aotitlelight1: "res/青タイトルの光1.png",
    aotitlelight2: "res/青タイトルの光2.png",
    aotitlelight3: "res/青タイトルの光3.png",
    aotitlelight4: "res/青タイトルの光4.png",
    aotitlelight5: "res/青タイトルの光5.png",
    aotitlelight6: "res/青タイトルの光6.png",
    aotitlelight7: "res/青タイトルの光7.png",
    aititlelight1: "res/藍タイトルの光1.png",
    aititlelight2: "res/藍タイトルの光2.png",
    aititlelight3: "res/藍タイトルの光3.png",
    aititlelight4: "res/藍タイトルの光4.png",
    aititlelight5: "res/藍タイトルの光5.png",
    aititlelight6: "res/藍タイトルの光6.png",
    aititlelight7: "res/藍タイトルの光7.png",
    murasakititlelight1: "res/紫タイトルの光1.png",
    murasakititlelight2: "res/紫タイトルの光2.png",
    murasakititlelight3: "res/紫タイトルの光3.png",
    murasakititlelight4: "res/紫タイトルの光4.png",
    murasakititlelight5: "res/紫タイトルの光5.png",
    murasakititlelight6: "res/紫タイトルの光6.png",
    murasakititlelight7: "res/紫タイトルの光7.png",
    titlelight1: "res/タイトルの光1.png",
    titlelight2: "res/タイトルの光2.png",
    titlelight3: "res/タイトルの光3.png",
    titlelight4: "res/タイトルの光4.png",
    titlelight5: "res/タイトルの光5.png",
    titlelight6: "res/タイトルの光6.png",
    titlelight7: "res/タイトルの光7.png",
    toumei: "res/透明.png",

    greenslime1: "res/グリーンスライム1.png",
    greenslime2: "res/グリーンスライム2.png",
    greenslime3: "res/グリーンスライム3.png",
    greenslime4: "res/グリーンスライム4.png",
    greenslime5: "res/グリーンスライム5.png",
    greenslime6: "res/グリーンスライム6.png",
    greenslime7: "res/グリーンスライム7.png",
    greenslime8: "res/グリーンスライム8.png",
    greenslime9: "res/グリーンスライム9.png",
    greenslime10: "res/グリーンスライム10.png",
    greenslime11: "res/グリーンスライム11.png",
    greenslime12: "res/グリーンスライム12.png",
    greenslime13: "res/グリーンスライム13.png",
    greenslime14: "res/グリーンスライム14.png",
    greenslime15: "res/グリーンスライム15.png",
    greenslime16: "res/グリーンスライム16.png",

    kinslime1: "res/ゴールデンスライム1.png",
    kinslime2: "res/ゴールデンスライム2.png",
    kinslime3: "res/ゴールデンスライム3.png",
    kinslime4: "res/ゴールデンスライム4.png",
    kinslime5: "res/ゴールデンスライム5.png",
    kinslime6: "res/ゴールデンスライム6.png",
    kinslime7: "res/ゴールデンスライム7.png",
    kinslime8: "res/ゴールデンスライム8.png",
    kinslime9: "res/ゴールデンスライム9.png",
    kinslime10: "res/ゴールデンスライム10.png",
    kinslime11: "res/ゴールデンスライム11.png",
    kinslime12: "res/ゴールデンスライム12.png",

    akaslime1: "res/アシッドスライム1.png",
    akaslime2: "res/アシッドスライム2.png",
    akaslime3: "res/アシッドスライム3.png",
    akaslime4: "res/アシッドスライム4.png",
    akaslime5: "res/アシッドスライム5.png",
    akaslime6: "res/アシッドスライム6.png",
    akaslime7: "res/アシッドスライム7.png",
    akaslime8: "res/アシッドスライム8.png",
    akaslime9: "res/アシッドスライム9.png",
    akaslime10: "res/アシッドスライム10.png",
    akaslime11: "res/アシッドスライム11.png",
    akaslime12: "res/アシッドスライム12.png",

    zonbi1: "res/コープス1.png",
    zonbi2: "res/コープス2.png",
    zonbi3: "res/コープス3.png",
    zonbi4: "res/コープス4.png",
    zonbi5: "res/コープス5.png",
    zonbi6: "res/コープス6.png",
    zonbi7: "res/コープス7.png",
    zonbi8: "res/コープス8.png",

    bat1: "res/ヴァンパイアバット1.png",
    bat2: "res/ヴァンパイアバット2.png",
    bat3: "res/ヴァンパイアバット3.png",
    bat4: "res/ヴァンパイアバット4.png",

    doukoin1: "res/銅コイン1.png",
    doukoin2: "res/銅コイン2.png",
    doukoin3: "res/銅コイン3.png",
    doukoin4: "res/銅コイン4.png",
    doukoin5: "res/銅コイン5.png",
    doukoin6: "res/銅コイン6.png",
    doukoin7: "res/銅コイン7.png",
    doukoin8: "res/銅コイン8.png",

    kinkoin1: "res/金コイン1.png",
    kinkoin2: "res/金コイン2.png",
    kinkoin3: "res/金コイン3.png",
    kinkoin4: "res/金コイン4.png",
    kinkoin5: "res/金コイン5.png",
    kinkoin6: "res/金コイン6.png",
    kinkoin7: "res/金コイン7.png",
    kinkoin8: "res/金コイン8.png",

    ginkoin1: "res/銀コイン1.png",
    ginkoin2: "res/銀コイン2.png",
    ginkoin3: "res/銀コイン3.png",
    ginkoin4: "res/銀コイン4.png",
    ginkoin5: "res/銀コイン5.png",
    ginkoin6: "res/銀コイン6.png",
    ginkoin7: "res/銀コイン7.png",
    ginkoin8: "res/銀コイン8.png",




};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
